package com.autoshorts.ai.entity;

public enum GenerationStep {
    QUEUED,
    CONTENT_PREPARATION,
    SCRIPT_GENERATION,
    AUDIO_SYNTHESIS,
    SUBTITLE_GENERATION,
    VISUAL_ASSET_GENERATION,
    VIDEO_COMPOSITION,
    COMPLETED
}
